resolver: lts-11.18
packages:
- '.'
- location:
    git: git://github.com/dylex/waimwork
    commit: 4ac02af8e56cf26235737a964e08bce5a5f22305
  extra-dep: true
- location:
    git: git://github.com/dylex/hs-hdf5
    commit: 7f3da0a759d69326031c0ff7a4c6419da57c39fb
  extra-dep: true
extra-deps:
  - web-inv-route-0.1.2.1
flags:
  web-inv-route:
    snap: false
    happstack: false
