resolver: lts-13.28
packages:
- '.'
extra-deps:
  - postgresql-typed-0.6.0.1
  - web-inv-route-0.1.2.2
  - git: git://github.com/dylex/waimwork
    commit: fe4b01f09c12d2419d1b208aed79b04e0de8b227
  - git: git://github.com/dylex/hs-hdf5
    commit: ee4a09ada76b87ea2f7f88661c5b3049d9d9625c
flags:
  web-inv-route:
    snap: false
    happstack: false
